apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres.yaml
  - redis.yaml
  - rabbitmq.yaml
  - minio.yaml
  #- smtp-relay.yaml
  - backend.yaml
  - worker-post-backup.yaml
  - worker-email-otp.yaml
  - worker-newsletter.yaml
  - moderation.yaml
  - audit-maintenance.yaml
  - backup.yaml
  - frontend.yaml
  - cert-manager-issuer.yaml
  - certificate.yaml
  - ingress.yaml
  - middleware-security-headers.yaml
  - ingressroute.yaml
  - ingressroute-minio.yaml
