"""i18n posts/pages, follow, profile, social links

Revision ID: 07a5634edf75
Revises: 0767b8d527ec
Create Date: 2026-08-30 06:49:22.970851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07a5634edf75'
down_revision: Union[str, None] = '0767b8d527ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pages',
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('locale', sa.String(length=2), nullable=False),
    sa.Column('translation_group_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('updated_by_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', 'locale', name='uq_page_slug_locale'),
    sa.UniqueConstraint('translation_group_id', 'locale', name='uq_page_translation_group_locale')
    )
    op.create_index(op.f('ix_pages_slug'), 'pages', ['slug'], unique=False)
    op.create_index(op.f('ix_pages_translation_group_id'), 'pages', ['translation_group_id'], unique=False)
    op.create_table('social_links',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_follows',
    sa.Column('follower_id', sa.UUID(), nullable=False),
    sa.Column('followed_user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('follower_id != followed_user_id', name='ck_user_follow_not_self'),
    sa.ForeignKeyConstraint(['followed_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'followed_user_id', name='uq_user_follow_pair')
    )
    op.create_table('blog_follows',
    sa.Column('follower_id', sa.UUID(), nullable=False),
    sa.Column('blog_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'blog_id', name='uq_blog_follow_pair')
    )
    # server_default esplicito: senza, l'ALTER fallirebbe su righe già esistenti
    # (blog/post creati prima dell'introduzione dell'i18n). gen_random_uuid() è
    # nativo in Postgres 13+, nessuna estensione richiesta.
    op.add_column(
        'blogs',
        sa.Column('default_locale', sa.String(length=2), server_default=sa.text("'it'"), nullable=False),
    )
    op.add_column(
        'posts',
        sa.Column('locale', sa.String(length=2), server_default=sa.text("'it'"), nullable=False),
    )
    op.add_column(
        'posts',
        sa.Column(
            'translation_group_id',
            sa.UUID(),
            server_default=sa.text('gen_random_uuid()'),
            nullable=False,
        ),
    )
    op.drop_constraint(op.f('uq_post_blog_slug'), 'posts', type_='unique')
    op.create_index(op.f('ix_posts_translation_group_id'), 'posts', ['translation_group_id'], unique=False)
    op.create_unique_constraint('uq_post_blog_slug_locale', 'posts', ['blog_id', 'slug', 'locale'])
    op.create_unique_constraint('uq_post_translation_group_locale', 'posts', ['translation_group_id', 'locale'])
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('avatar_object_key', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_object_key')
    op.drop_column('users', 'bio')
    op.drop_constraint('uq_post_translation_group_locale', 'posts', type_='unique')
    op.drop_constraint('uq_post_blog_slug_locale', 'posts', type_='unique')
    op.drop_index(op.f('ix_posts_translation_group_id'), table_name='posts')
    op.create_unique_constraint(op.f('uq_post_blog_slug'), 'posts', ['blog_id', 'slug'], postgresql_nulls_not_distinct=False)
    op.drop_column('posts', 'translation_group_id')
    op.drop_column('posts', 'locale')
    op.drop_column('blogs', 'default_locale')
    op.drop_table('blog_follows')
    op.drop_table('user_follows')
    op.drop_table('social_links')
    op.drop_index(op.f('ix_pages_translation_group_id'), table_name='pages')
    op.drop_index(op.f('ix_pages_slug'), table_name='pages')
    op.drop_table('pages')
    # ### end Alembic commands ###
