"""opt-in crawler motori di ricerca e IA per blog e post

Revision ID: 139cf285ee44
Revises: c5c5ea3b5cf6
Create Date: 2026-09-06 16:59:23.254931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '139cf285ee44'
down_revision: Union[str, None] = 'c5c5ea3b5cf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default per popolare le righe esistenti (blogs non è vuota) al
    # momento dell'ALTER TABLE; il default a livello applicativo resta in
    # app/models/blog.py, qui serve solo per la migrazione stessa.
    op.add_column(
        'blogs',
        sa.Column('search_indexing_enabled', sa.Boolean(), nullable=False, server_default=sa.text('true')),
    )
    op.add_column(
        'blogs',
        sa.Column('ai_crawling_enabled', sa.Boolean(), nullable=False, server_default=sa.text('true')),
    )
    op.alter_column('blogs', 'search_indexing_enabled', server_default=None)
    op.alter_column('blogs', 'ai_crawling_enabled', server_default=None)
    op.add_column('posts', sa.Column('search_indexing_enabled', sa.Boolean(), nullable=True))
    op.add_column('posts', sa.Column('ai_crawling_enabled', sa.Boolean(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'ai_crawling_enabled')
    op.drop_column('posts', 'search_indexing_enabled')
    op.drop_column('blogs', 'ai_crawling_enabled')
    op.drop_column('blogs', 'search_indexing_enabled')
    # ### end Alembic commands ###
