"""frammenti evidenziati dai lettori

Revision ID: 98da258b5f92
Revises: ef332d4924b0
Create Date: 2026-09-04 18:07:43.700583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98da258b5f92'
down_revision: Union[str, None] = 'ef332d4924b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_fragments',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'post_id', 'text', name='uq_post_fragment_user_post_text')
    )
    op.create_index(op.f('ix_post_fragments_post_id'), 'post_fragments', ['post_id'], unique=False)
    op.create_index(op.f('ix_post_fragments_user_id'), 'post_fragments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_fragments_user_id'), table_name='post_fragments')
    op.drop_index(op.f('ix_post_fragments_post_id'), table_name='post_fragments')
    op.drop_table('post_fragments')
    # ### end Alembic commands ###
