"""post categories

Revision ID: b16963e9cdcb
Revises: d5dbeeb3f79f
Create Date: 2026-08-31 21:07:18.383606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b16963e9cdcb'
down_revision: Union[str, None] = 'd5dbeeb3f79f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('blog_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blog_id', 'slug', name='uq_category_blog_slug')
    )
    op.add_column('posts', sa.Column('category_id', sa.UUID(), nullable=True))
    # nome esplicito: l'autogenerate lo lascerebbe anonimo (None), rendendo
    # impossibile un downgrade pulito (drop_constraint ha bisogno di un nome).
    op.create_foreign_key(
        'fk_posts_category_id_categories', 'posts', 'categories', ['category_id'], ['id'], ondelete='SET NULL'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_posts_category_id_categories', 'posts', type_='foreignkey')
    op.drop_column('posts', 'category_id')
    op.drop_table('categories')
    # ### end Alembic commands ###
