"""frammenti pubblici o privati

Revision ID: c5c5ea3b5cf6
Revises: 7981bf8eb571
Create Date: 2026-09-06 16:24:51.449941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5c5ea3b5cf6'
down_revision: Union[str, None] = '7981bf8eb571'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default: righe già esistenti diventano "private" (comportamento
    # storico, prima che questo campo esistesse), nessun fallimento su NOT NULL.
    op.add_column(
        'post_fragments',
        sa.Column('is_public', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post_fragments', 'is_public')
    # ### end Alembic commands ###
