"""blog cover image and favicon

Revision ID: c5e9f0a1b2d3
Revises: b4d8e9f0a1c2
Create Date: 2026-09-14 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'c5e9f0a1b2d3'
down_revision: Union[str, None] = 'b4d8e9f0a1c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('cover_image_url', sa.String(length=2048), nullable=True))
    # server_default: blogs ha già righe, non c'è modo di aggiungere colonne
    # NOT NULL senza un default su una tabella non vuota.
    op.add_column(
        'blogs',
        sa.Column('cover_image_is_sensitive', sa.Boolean(), nullable=False, server_default='false'),
    )
    op.add_column(
        'blogs',
        sa.Column(
            'cover_image_categories',
            postgresql.ARRAY(sa.String(length=20)),
            nullable=False,
            server_default='{}',
        ),
    )
    op.add_column('blogs', sa.Column('favicon_object_key', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'favicon_object_key')
    op.drop_column('blogs', 'cover_image_categories')
    op.drop_column('blogs', 'cover_image_is_sensitive')
    op.drop_column('blogs', 'cover_image_url')
    # ### end Alembic commands ###
