"""post cover image sensitivity flag

Revision ID: d5dbeeb3f79f
Revises: f3ed30401d5f
Create Date: 2026-08-31 20:51:56.077791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5dbeeb3f79f'
down_revision: Union[str, None] = 'f3ed30401d5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default: posts ha già righe, non c'è modo di aggiungere una
    # colonna NOT NULL senza un default su una tabella non vuota.
    op.add_column(
        'posts', sa.Column('cover_image_is_sensitive', sa.Boolean(), nullable=False, server_default='false')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'cover_image_is_sensitive')
    # ### end Alembic commands ###
