"""platform_config audit retention days

Revision ID: d7f0a1b2c3e4
Revises: c5e9f0a1b2d3
Create Date: 2026-09-14 00:00:00.000001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7f0a1b2c3e4'
down_revision: Union[str, None] = 'c5e9f0a1b2d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default: platform_config ha già (al più) una riga, stesso
    # principio delle altre colonne NOT NULL aggiunte dopo il B6.
    op.add_column(
        'platform_config',
        sa.Column('audit_retention_days', sa.Integer(), nullable=False, server_default='105'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('platform_config', 'audit_retention_days')
    # ### end Alembic commands ###
