"""post cover image url

Revision ID: e416be915439
Revises: 2807a24ea58f
Create Date: 2026-08-30 17:49:52.942304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e416be915439'
down_revision: Union[str, None] = '2807a24ea58f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('cover_image_url', sa.String(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'cover_image_url')
    # ### end Alembic commands ###
