"""platform_config footer columns and bottom bar

Revision ID: e8a1b2c3d4f5
Revises: d7f0a1b2c3e4
Create Date: 2026-09-14 00:00:00.000002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8a1b2c3d4f5'
down_revision: Union[str, None] = 'd7f0a1b2c3e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platform_config', sa.Column('footer_column1_markdown', sa.Text(), nullable=True))
    op.add_column('platform_config', sa.Column('footer_column2_markdown', sa.Text(), nullable=True))
    # colonna 3: mai sovrascrivibile dal blog (a differenza di 1/2), vedi
    # app/domain/blog_config.py e frontend/src/components/shell/SiteFooter.tsx
    op.add_column('platform_config', sa.Column('footer_column3_markdown', sa.Text(), nullable=True))
    # barra inferiore: sempre e solo di piattaforma, nessun override possibile
    op.add_column('platform_config', sa.Column('footer_bottom_bar_markdown', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('platform_config', 'footer_bottom_bar_markdown')
    op.drop_column('platform_config', 'footer_column3_markdown')
    op.drop_column('platform_config', 'footer_column2_markdown')
    op.drop_column('platform_config', 'footer_column1_markdown')
    # ### end Alembic commands ###
