"""media e link citati nei post, categorie di avviso

Revision ID: ef332d4924b0
Revises: 9fca56e73604
Create Date: 2026-09-03 20:24:11.628807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef332d4924b0'
down_revision: Union[str, None] = '9fca56e73604'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_links',
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('link_text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'position')
    )
    op.create_table('post_media',
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('alt_text', sa.Text(), nullable=False),
    sa.Column('categories', sa.ARRAY(sa.String(length=20)), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'position')
    )
    # server_default: posts ha già righe, non c'è modo di aggiungere una
    # colonna NOT NULL senza un default esplicito (stesso schema già usato
    # per users.fallback_languages).
    op.add_column(
        'posts',
        sa.Column('cover_image_categories', sa.ARRAY(sa.String(length=20)), nullable=False, server_default='{}'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'cover_image_categories')
    op.drop_table('post_media')
    op.drop_table('post_links')
    # ### end Alembic commands ###
