"""profile bio fields and blog default author name

Revision ID: f3ed30401d5f
Revises: bd9a65e7bdd4
Create Date: 2026-08-31 19:12:48.182282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3ed30401d5f'
down_revision: Union[str, None] = 'bd9a65e7bdd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('default_author_display_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('country', sa.String(length=2), nullable=True))
    op.add_column('users', sa.Column('native_language', sa.String(length=2), nullable=True))
    # server_default: users ha già righe, non c'è modo di aggiungere una
    # colonna NOT NULL senza un default su una tabella non vuota.
    op.add_column(
        'users',
        sa.Column('fallback_languages', sa.ARRAY(sa.String(length=2)), nullable=False, server_default='{}'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'fallback_languages')
    op.drop_column('users', 'native_language')
    op.drop_column('users', 'country')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('blogs', 'default_author_display_name')
    # ### end Alembic commands ###
